### ISSUE TITLE
/gazebo/set_physics_properties] is now available

### ISSUE THREAD

**Issue by ge3088** [KumarRobotics/mrsl_quadrotor#16]
Hello,

I am encountering an error when launching the turtlebot world. It's launching; however, I don't see the the objects. I am using ubuntu 18.04. the error I am getting is: [ INFO] [1592854608.402762003]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[Err] [REST.cc:205] Error in REST request

below is the terminal output.

command: roslaunch turtlebot3_gazebo turtlebot3_world.launch
... logging to /home/bilal/.ros/log/b53d587c-b4bf-11ea-a063-185e0f0f7242/roslaunch-bilal-ThinkPad-T450-951.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://bilal-ThinkPad-T450:44075/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.6
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [967]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b53d587c-b4bf-11ea-a063-185e0f0f7242
process[rosout-1]: started with pid [979]
started core service [/rosout]
process[gazebo-2]: started with pid [985]
process[gazebo_gui-3]: started with pid [991]
process[spawn_urdf-4]: started with pid [996]
[ INFO] [1592854607.713844715]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1592854607.716364730]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1592854607.828642562]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1592854607.831616783]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1592854608.402762003]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
[ INFO] [1592854609.009003599, 0.109000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1592854609.013426175, 0.109000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1592854609.204888967, 0.109000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1592854609.206066058, 0.109000000]: Starting Laser Plugin (ns = /)
[ INFO] [1592854609.209856483, 0.109000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1592854609.213681435, 0.109000000]: Physics dynamic reconfigure ready.
[ INFO] [1592854609.309894575, 0.109000000]: Starting plugin DiffDrive(ns = //)
[ INFO] [1592854609.310169675, 0.109000000]: DiffDrive(ns = //): <rosDebugLevel> = na
[ INFO] [1592854609.311137348, 0.109000000]: DiffDrive(ns = //): <tf_prefix> = 
[ INFO] [1592854609.313227576, 0.109000000]: DiffDrive(ns = //): Advertise joint_states
[ INFO] [1592854609.314707565, 0.109000000]: DiffDrive(ns = //): Try to subscribe to cmd_vel
[ INFO] [1592854609.317900293, 0.109000000]: DiffDrive(ns = //): Subscribe to cmd_vel
[ INFO] [1592854609.318926737, 0.109000000]: DiffDrive(ns = //): Advertise odom on odom 
[spawn_urdf-4] process has finished cleanly
log file: /home/bilal/.ros/log/b53d587c-b4bf-11ea-a063-185e0f0f7242/spawn_urdf-4*.log

**Comment by kartikmohta** [comment]
Please try the solution mentioned in https://answers.gazebosim.org/question/25030/gazebo-error-restcc205-error-in-rest-request/

**Comment by ge3088** [comment]
Thank you. I already tried that and I am still running into an issue. 

 roslaunch turtlebot3_gazebo turtlebot3_world.launch
... logging to /home/bilal/.ros/log/e7e3ea3c-b4cb-11ea-a063-185e0f0f7242/roslaunch-bilal-ThinkPad-T450-11580.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://bilal-ThinkPad-T450:38077/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.6
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [11593]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e7e3ea3c-b4cb-11ea-a063-185e0f0f7242
process[rosout-1]: started with pid [11604]
started core service [/rosout]
process[gazebo-2]: started with pid [11610]
process[gazebo_gui-3]: started with pid [11616]
process[spawn_urdf-4]: started with pid [11621]
[ INFO] [1592859846.838927987]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1592859846.841015095]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[gazebo-2] process has died [pid 11610, exit code 255, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode /opt/ros/melodic/share/turtlebot3_gazebo/worlds/turtlebot3_world.world __name:=gazebo __log:=/home/bilal/.ros/log/e7e3ea3c-b4cb-11ea-a063-185e0f0f7242/gazebo-2.log].
log file: /home/bilal/.ros/log/e7e3ea3c-b4cb-11ea-a063-185e0f0f7242/gazebo-2*.log

**Comment by kartikmohta** [comment]
This issue seems to a gazebo problem and is not related to anything in this repository, so you might want to ask on the relevant gazebo forums.
