### ISSUE TITLE
error [InsertModelWidget.cc:302] Missing model.config for mode  and  wating for service/gazebospawn_urdf_mode

### ISSUE THREAD

**Issue by cankancelik** [KumarRobotics/mrsl_quadrotor#18]
First of all thanks for your beautiful work. However;  when I call the launch file, there are two problems occurring for two different commands as follows;
(Ubuntu 18.04, ROS Melodic, Gazebo 9, quadrotor_control build)

1) For the **roslaunch gazebo.launch world:=levine**  error is;
_[InsertModelWidget.cc:302] Missing model.config for model_

For another issue, it is said that can be ignored but after 1 hour of waiting nothing appeared on the screen. 

2) For the  **roslaunch mrsl_quadrotor_launch spawn.launch mav_type:=dragon_ddk mav_name:=ddkmodel**  there is no error code yet terminal stuck where the following line shows up
_wating for service/gazebospawn_urdf_model_

Thank you in advance.

**Comment by MF-Ahmed** [comment]
Hi I am having the issue with the  models  when running roslaunch mrsl_quadrotor_launch gazebo.launch world:=levine
on ubunto 20.04, ROS Noetic. 
Do I need to change  <env name="GAZEBO_MODEL_PATH" value="$(find mrsl_models)/models:$(optenv GAZEBO_MODEL_PATH)"/> 
in mrsl_quadrotor_launch gazebo.launch

Thanks 

[ INFO] [1696340325.628142004, 0.005000000]: Physics dynamic reconfigure ready.
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/D60"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/falcon4"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/fla_hotel"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/fla_hotel_3doors"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/fla_office"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/forest0"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/hummingbird"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/levine"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/office"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/pelican"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/pillars"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/sensors"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/skir"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_models/models/wg"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/opt/ros/noetic/share/turtlebot3_gazebo/models/turtlebot3_autorace"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/opt/ros/noetic/share/turtlebot3_gazebo/models/turtlebot3_autorace_2020"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/opt/ros/noetic/share/turtlebot3_gazebo/models/turtlebot3_common_meshes"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_quadrotor_description/urdf"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/usr/data/ExplOrbSLAM_Multirobot/src/kumarquad/catkin_ws/src/mrsl_quadrotor/mrsl_quadrotor_description/worlds"

**Comment by ngocquynhle** [comment]
Hi @MF-Ahmed
Have you solved this problem?
