### ISSUE TITLE
roslaunch error [InsertModelWidget.cc:302] Missing model.config for model

### ISSUE THREAD

**Issue by tomcattigerkkk** [KumarRobotics/mrsl_quadrotor#4]
Thanks to your great work, but when I tried to test the launch file. There is a problem. 
After successfully catkin_make, I've tried to launch the world using `roslaunch gazebo.launch world:=levine`. Then the error 
`[InsertModelWidget.cc:302] Missing model.config for model`
for every model comes. 
I'm not sure if I've set up something wrong. Could you give me some suggestion?

---
Also maybe a small issue. The package may require 'quadrotor_msgs' package and in the package the code for 'QuadrotorSO3AttitudeControl.cpp' line 67-69 'cmd' doesn't have 'angular_velocity' unless one adds a message in 'SO3COmmand.msg' with 'geometry_msgs/Vector3 angular_velocity'. Is that true?

Thanks.

**Comment by tomcattigerkkk** [comment]
@sikang Thank you for your replay. I'm using ROS (Kinetic) Ubuntu 16.04 with Gazebo 7.14. 
---
@kartikmohta 
thank you for your suggestion of quadrotor_msgs. 
It seems the error comes from 
'gzclient: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:252：void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assume ‘(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"’ failed.'
And then the core was dumped. Is it because of the version my orge?

**Comment by tomcattigerkkk** [comment]
@sikang 
It works. Thanks a lot!

**Comment by SystemDiagnosticss** [comment]
@tomcattigerkkk @sikang Hello. Can you help me?:) How you downgrade Gazebo?) I am remove my Gazebo 7.14 and install it again use this instruction http://gazebosim.org/tutorials?cat=install&tut=install_ubuntu&ver=7.0 . But was installed 7.14 again:) How I can install 7.0 version?

**Comment by sikang** [comment]
This is how I downgrade: https://github.com/KumarRobotics/mrsl_quadrotor/issues/4#issuecomment-413156390 
Remove that osrf ppa dependancy is critical, otherwise it will download the latest gazebo.
