### ISSUE TITLE
Missing quadrotor_control

### ISSUE THREAD

**Issue by ArlenCHEN** [KumarRobotics/mrsl_quadrotor#5]
@sikang @tdinesh @ljarin

Dear authors,
Thanks for your this open-source simulator! But can you provide the `quadrotor_control` package, which is listed as one of requirements in README? The link you put there is invalid now. Thanks!

**Comment by tdinesh** [comment]
`quadrotor_control` package is not open-sourced yet. It will be released in next few months (May end). Stay tuned.

**Comment by ArlenCHEN** [comment]
Thanks anyway!
